### ISSUE TITLE
Possible typos in PDF?

### ISSUE THREAD

**Issue by Mperonen** [codemeow/xlibmanual#1]
First, I would like to state that your introduction into Xlib is absolutely fantastic. I'm currently going through your PDF and I am trying to get a hang on the X window environment and programming using it.

To support your awesome work, even though it is an older document, I would like to ask if I noticed a possible error in your document?

At the beginning there is your email, but it seems not t work anymore.

**On page 22:**
"Keyboard Press And Release Events
If a window controlled by our program currently holds the keyboard focus, it can receive key press
and key release events. In order to register for such events, any of the following masks may be added to
the call to XSelectInput():
KeyPressMask
// Notify our program when a key was pressed while any of its controlled windows
// had the keyboard focus.
**KeyPressMask                                              <--- Should this line be "KeyReleaseMask"?**
// Notify our program when a key was released while any of its controlled windows
// had the keyboard focus."

Thank you! I will keep reading and I will inform if I notice more.

**Comment by codemeow** [comment]
Thank you for your work.

First of all I'd like to clarify once more that I'm not the original author of the documentation as I'm only adapted it to PDF. The original link is already dead and you can only see it at https://web.archive.org/web/20071018025425/http://users.actcom.co.il/~choo/lupg/tutorials/xlib-programming/xlib-programming.html . 

It is indeed a typo in the original document. I will correct my files when I can, thank you.

**Comment by Mperonen** [comment]
Oh thank you for your response! I will see if I can find and contact the original author. Always enjoy a little detective work :)

**Comment by codemeow** [comment]
Fixed, thank you!
